openapi: 3.0.0
info:
  title: My API
  description: Description
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /signup:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  example: any
                email:
                  example: any
                password:
                  example: any
                pic:
                  example: any
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
  /signin:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  example: any
                password:
                  example: any
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
  /reset-password:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  example: any
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
  /new-password:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  example: any
                token:
                  example: any
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
  /allpost:
    get:
      description: ""
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /getsubpost:
    get:
      description: ""
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /createpost:
    post:
      description: ""
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  example: any
                body:
                  example: any
                pic:
                  example: any
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
  /mypost:
    get:
      description: ""
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /like:
    put:
      description: ""
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  example: any
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
  /unlike:
    put:
      description: ""
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  example: any
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
  /comment:
    put:
      description: ""
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  example: any
                postId:
                  example: any
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
  /deletepost/{postId}:
    delete:
      description: ""
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
        - name: authorization
          in: header
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
  /user/{id}:
    get:
      description: ""
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: authorization
          in: header
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '422':
          description: Unprocessable Entity
  /follow:
    put:
      description: ""
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                followId:
                  example: any
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
  /unfollow:
    put:
      description: ""
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                unfollowId:
                  example: any
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
  /updatepic:
    put:
      description: ""
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pic:
                  example: any
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
  /search-users:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  example: any
      responses:
        '200':
          description: OK
