openapi: 3.0.0
info:
  title: My API
  description: Description
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /healthz:
    summary: Healthcheck endpoint
    get:
      summary: Healthcheck
      operationId: Healthcheck
      responses:
        "200":
          description: Healthy response
  